name: Match Consulting Inc.
favicon: null
layout_spectrum: 0.7972171758301556
typography_spectrum: 0.80314
title: 'Match Consulting Main Website '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.7043948376085609
  lightness: 0.5625
  saturation: 0.47797075542621315
  rhythmicContrast: 0.8514260239899158
purpose: []
